<?php

namespace Bettingup\TicketBundle\Entity;

trait Team
{
    public function getTeams()
    {
        return [
            "Ajaccio",
            "Bastia",
            "Bordeaux",
            "Evian",
            "Guingamp",
            "Lille",
            "Lorient",
            "Lyon",
            "Marseille",
            "Monaco",
            "Montpellier",
            "Nantes",
            "Nice",
            "Paris St-G.",
            "Rennes",
            "Sochaux",
            "St-Etienne",
            "Stade de Reims",
            "Toulouse",
            "Valenciennes",
            "Augsburg",
            "B Dortmund",
            "B Leverkusen",
            "B Munich",
            "Braunschweig",
            "E. Frankfurt",
            "Freiburg",
            "Hamburg",
            "Hannover",
            "Hertha Berlin",
            "Hoffenheim",
            "M'gladbach",
            "Mainz",
            "Nuremberg",
            "Schalke",
            "Stuttgart",
            "W Bremen",
            "Wolfsburg",
            "Anderlecht",
            "Cercle Bruges",
            "Charleroi",
            "FC Bruges",
            "Genk",
            "Gent",
            "Kortrikj",
            "Lierse",
            "Lokeren",
            "Mechelen",
            "O-H Leuven",
            "Oostende",
            "RAEC Mons B",
            "Standard Liege",
            "W Beveren",
            "Waregem",
            "Apollon Smyrni",
            "Aris Salonika",
            "Asteras T.",
            "Atromitos",
            "Ergotelis",
            "Ioannina",
            "Kalloni",
            "Levadiakos",
            "OFI Crete",
            "Olympiakos",
            "PAOK Salonika",
            "Panathinaikos",
            "Panetolikos",
            "Panionios",
            "Panthrakikos K",
            "Platanias",
            "Veroia",
            "Xanthi",
            "Atalanta",
            "Bologna",
            "Cagliari",
            "Catania",
            "Chievo",
            "Fiorentina",
            "Genoa",
            "Inter",
            "Juventus",
            "Lazio",
            "Livorno",
            "Milan",
            "Napoli",
            "Parma",
            "Roma",
            "Sampdoria",
            "Sassuolo",
            "Torino",
            "Udinese",
            "Verona",
            "Acad. Coimbra",
            "Arouca",
            "Belenenses",
            "Benfica",
            "Braga",
            "Estoril",
            "Gil Vicente",
            "Maritimo",
            "Nacional",
            "Olhanense",
            "Pacos Ferreira",
            "Porto",
            "Rio Ave",
            "Sporting Lisbon",
            "V Guimaraes",
            "Vitoria Setubal",
            "Almeria",
            "Ath Bilbao",
            "Atl Madrid",
            "Barcelona",
            "Celta Vigo",
            "Elche",
            "Espanyol",
            "Getafe",
            "Granada",
            "Levante",
            "Malaga",
            "Osasuna",
            "R. Vallecano",
            "Real Betis",
            "Real Madrid",
            "Seville",
            "Sociedad",
            "Valencia",
            "Valladolid",
            "Villarreal",
            "Alaves",
            "Alcorcon",
            "Barcelona B",
            "Cordoba",
            "Deportivo",
            "Eibar",
            "Girona",
            "Hercules",
            "Jaen",
            "Las Palmas",
            "Lugo",
            "Mallorca",
            "Mirandes",
            "Murcia",
            "Numancia",
            "Ponferradina",
            "Real Madrid B",
            "Recreativo",
            "Sabadell",
            "Sp. Gijon",
            "Tenerife",
            "Zaragoza",
            "Albania",
            "Andorra",
            "Armenia",
            "Austria",
            "Azerbaijan",
            "Belarus",
            "Belgium",
            "Bosnia",
            "Bulgaria",
            "Croatia",
            "Cyprus",
            "Czech Rep",
            "Denmark",
            "England",
            "Estonia",
            "Faroe Islands",
            "Finland",
            "France",
            "Georgia",
            "Germany",
            "Greece",
            "Holland",
            "Hungary",
            "Iceland",
            "Ireland",
            "Israel",
            "Italy",
            "Kazakhstan",
            "Latvia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Malta",
            "Moldova",
            "Montenegro",
            "N Ireland",
            "Norway",
            "Poland",
            "Portugal",
            "Romania",
            "Russia",
            "San Marino",
            "Scotland",
            "Serbia",
            "Slovakia",
            "Slovenia",
            "Spain",
            "Sweden",
            "Switzerland",
            "Turkey",
            "Ukraine",
            "Wales",
            "Arsenal",
            "Aston Villa",
            "C Palace",
            "Cardiff",
            "Chelsea",
            "Everton",
            "Fulham",
            "Hull",
            "Liverpool",
            "Man City",
            "Man Utd",
            "Newcastle",
            "Norwich",
            "Southampton",
            "Stoke",
            "Sunderland",
            "Swansea",
            "Tottenham",
            "West Brom",
            "West Ham",
            "Barnsley",
            "Birmingham",
            "Blackburn",
            "Blackpool",
            "Bolton",
            "Bournemouth",
            "Brighton",
            "Burnley",
            "Charlton",
            "Derby",
            "Doncaster",
            "Huddersfield",
            "Ipswich",
            "Leeds",
            "Leicester",
            "Middlesbro",
            "Millwall",
            "Nottm Forest",
            "QPR",
            "Reading",
            "Sheff Wed",
            "Watford",
            "Wigan",
            "Yeovil",
        ];
    }
}
