bettingup_ticket:
    resource: "@BettingupTicketBundle/Controller/"
    prefix:   /
    type: annotation

bettingup_core:
    resource: "@BettingupCoreBundle/Controller/"
    prefix:   /
    type: annotation

bettingup_user:
    resource: "@BettingupUserBundle/Controller/"
    prefix:   /
    type: annotation

# bettingup_api:
#     resource: "@BettingupApiBundle/Controller/"
#     prefix:   /
#     type: annotation

api_bettingup_user:
    resource: "@BettingupUserBundle/Resources/config/routing.yml"
    prefix:   /
    type: rest

api_bettingup_ticket:
    resource: "@BettingupTicketBundle/Resources/config/routing.yml"
    prefix:   /
    type: rest
