imports:
    - { resource: config.yml }

doctrine:
    dbal:
        connections:
            default:
                dbname:   %database_test%

monolog:
    handlers:
        main:
            formatter: ~